import './globals.css';
import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import { NextAuthProvider } from './provider';
import { Header } from '../components/commons';
import { Toaster } from 'react-hot-toast';

const outfit = Outfit({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang='fr'>
      <body className={`${outfit.className} layout__global`}>
        <NextAuthProvider>
          <Header />
          {children}
          <Toaster />
        </NextAuthProvider>
      </body>
    </html>
  );
};

export default RootLayout;
